import { Todo } from "./todo.model";

export const TODOS: Todo[]=[
    {id: 1, title: 'Learn Angular', completed: false},
    {id: 2, title: 'Learn React', completed: false},
    {id: 3, title: 'Learn Vue', completed: false},
    {id: 4, title: 'Learn Svelte', completed: false},
    {id: 5, title: 'Learn Web Components', completed: false},
    // {id: 6, title: 'Learn Micro Frontends', completed: false},
    // {id: 7, title: 'Learn Microservices', completed: false},
    // {id: 8, title: 'Learn Docker', completed: false},
    // {id: 9, title: 'Learn Kubernetes', completed: false},
    // {id: 10, title: 'Learn AWS', completed: false},
    // {id: 11, title: 'Learn Azure', completed: false},
    // {id: 12, title: 'Learn GCP', completed: false},
    // {id: 13, title: 'Learn Java', completed: false},
    // {id: 14, title: 'Learn Python', completed: false},
    // {id: 15, title: 'Learn Ruby', completed: false},
    // {id: 16, title: 'Learn Go', completed: false},
    // {id: 17, title: 'Learn Rust', completed: false},
    // {id: 18, title: 'Learn C', completed: false},
    // {id: 19, title: 'Learn C++', completed: false},
    // {id: 20, title: 'Learn C#', completed: false},
    // {id: 21, title: 'Learn Swift', completed: false},
    // {id: 22, title: 'Learn Kotlin', completed: false},
    // {id: 23, title: 'Learn Scala', completed: false},
    // {id: 24, title: 'Learn Groovy', completed: false},
    // {id: 25, title: 'Learn TypeScript', completed: false},
    // {id: 26, title: 'Learn JavaScript', completed: false},
    // {id: 27, title: 'Learn HTML', completed: false},
    // {id: 28, title: 'Learn CSS', completed: false},
    // {id: 29, title: 'Learn SASS', completed: false},
    // {id: 30, title: 'Learn LESS', completed: false},
    // {id: 31, title: 'Learn Stylus', completed: false},
    // {id: 32, title: 'Learn Tailwind CSS', completed: false},
    // {id: 33, title: 'Learn Bootstrap', completed: false},
    // {id: 34, title: 'Learn Materialize', completed: false},
    // {id: 35, title: 'Learn Foundation', completed: false},
    // {id: 36, title: 'Learn Bulma', completed: false},
    // {id: 37, title: 'Learn Semantic UI', completed: false},
    // {id: 38, title: 'Learn Ionic', completed: false},
    // {id: 39, title: 'Learn React Native', completed: false},
    // {id: 40, title: 'Learn Flutter', completed: false},
];